### ISSUE TITLE
White theme?

### ISSUE THREAD

**Issue by scaledteam** [uowuo/abaddon#22]
Hi! I edited css file to make theme white, but one thing missing - default nickname color is white, so i can't see it in white background.
![1](https://user-images.githubusercontent.com/43995399/112729664-3340b880-8f4f-11eb-885f-d55d9b8db8ad.jpg)

This code didn't help. =(
```
.message-container-author text {
    color: @text_color;
}
```

**Comment by ouwou** [comment]
[this](https://github.com/uowuo/abaddon/commit/f4366fc0af088d7d78e2e571fb9b81e0c5693b51) should fix it
the css you would use would be
```css
.message-container-author {
    color: @text_color;
}
```
but if you are modifying the existing css you won't actually need that now because of [this part](https://github.com/uowuo/abaddon/blob/f4366fc0af088d7d78e2e571fb9b81e0c5693b51/css/main.css#L171-L173)
lemme know how it goes

**Comment by scaledteam** [comment]
Thank you, but i can't compile your program, therefore i used precompiled binaries. Can you help me with building?
First, 'nlohmann-json3-dev' and 'libsimpleini-dev' needed for compiling.
Second, i installed package with 'ConvertURF.h' file, it was 'llvm-11-dev', but i still get this error. I use Debian 11 (testing).
```
[ 36%] Built target ixwebsocket
[ 37%] Building CXX object CMakeFiles/abaddon.dir/abaddon.cpp.o
In file included from /home/scaled/git/abaddon/settings.hpp:4,
                 from /home/scaled/git/abaddon/abaddon.hpp:8,
                 from /home/scaled/git/abaddon/abaddon.cpp:13:
/usr/include/SimpleIni.h:2797:10: fatal error: ConvertUTF.h: No such file or directory
 2797 | #include "ConvertUTF.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/abaddon.dir/build.make:95: CMakeFiles/abaddon.dir/abaddon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/abaddon.dir/all] Error 2
```

**Comment by ouwou** [comment]
well the last CI run should have finished so you can use those binaries if you want
you shouldn't need to install anything like libsimpleini-dev since it's included as a git submodule. perhaps that package is conflicting somehow try removing it and recompiling it and make sure the submodule is init'd properly. ConvertUTF.h is also part of simpleini, not another package
if you still have problems with compiling then make another issue just so it's a bit more organized, i'll close this issue unless the color stuff is still broken
